name: Docker upload

on:
  push:
    paths:
     - "src/**"
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up QEMU 
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./src
        platforms: linux/arm
        push: true
        tags: rubensh/actions-runner:latest, rubensh/actions-runner:${{ github.run_number }}
